# Generated by Django 4.2.15 on 2024-09-15 07:03

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publish_in_telegram",
            field=models.CharField(
                choices=[(True, "Да"), (False, "Нет")],
                default=True,
                max_length=10,
                verbose_name="опубликовать в Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="текст"),
        ),
    ]
